import 'server-only';
import Mailgun from 'mailgun.js';
import FormData from 'form-data';

function getClient() {
  const mg = new Mailgun(FormData);
  return mg.client({ username: 'api', key: process.env.MAILGUN_API_KEY || '' });
}

// When APP_ENV is 'staging', every email this app sends gets a subject
// prefix (visible in an inbox list without opening the message — the main
// risk is mistaking a staging invite/reset link for a real one) plus a body
// banner, mirroring the equivalent staging banner comprobify's own emails
// already carry (see email.service.js's applyStagingBanner).
function stagingBannerText(locale: string) {
  return locale === 'en'
    ? "TEST ENVIRONMENT — this email was generated by Comprobify's staging environment and does not correspond to a production account."
    : 'ENTORNO DE PRUEBAS — este correo fue generado por el ambiente de staging de Comprobify y no corresponde a una cuenta de producción.';
}

function applyStagingMarker(
  { subject, text, html }: { subject: string; text: string; html: string },
  locale: string,
) {
  if (process.env.APP_ENV !== 'staging') return { subject, text, html };
  const banner = stagingBannerText(locale);
  const bannerHtml = `<div style="background:#fff3cd;border:1px solid #ffeeba;color:#856404;padding:10px 16px;margin-bottom:16px;border-radius:4px;font-weight:bold;">${banner}</div>`;
  return {
    subject: `[STAGING] ${subject}`,
    text: `${banner}\n\n${text}`,
    html: `${bannerHtml}\n${html}`,
  };
}

export async function sendMail({
  to,
  subject,
  text,
  html,
  locale = 'es',
}: {
  to: string;
  subject: string;
  text: string;
  html: string;
  /** Only used to localize the staging banner (APP_ENV === 'staging'); defaults to 'es'. */
  locale?: string;
}): Promise<void> {
  const domain = process.env.MAILGUN_DOMAIN;
  if (!domain || !process.env.MAILGUN_API_KEY) {
    throw new Error('MAILGUN_API_KEY/MAILGUN_DOMAIN not configured');
  }

  const marked = applyStagingMarker({ subject, text, html }, locale);

  const client = getClient();
  await client.messages.create(domain, {
    from: process.env.MAILGUN_FROM || `Comprobify <no-reply@${domain}>`,
    to,
    subject: marked.subject,
    text: marked.text,
    html: marked.html,
  });
}
