-- Switch every local primary key (and the foreign keys pointing at them) from
-- an autoincrement integer to a UUID (uuid v7, generated by Prisma on insert).
--
-- This is intentionally DESTRUCTIVE: it drops and recreates the tables rather
-- than backfilling parallel uuid columns, because no deployed database held
-- data worth preserving at the time this ran. Do NOT copy this approach for a
-- later schema change once real tenants exist.
--
-- The columns mirroring the Comprobify API's own ids are UUIDs too, because the
-- API is itself UUID-keyed (uuid_generate_v7() on every table — see its
-- db/migrations/001_create_issuers.sql, 023_create_api_keys.sql, 035_tenants.sql):
--   tenants.api_tenant_id, tenant_api_keys.api_key_id, issuers.api_issuer_id,
--   notifications.issuer_id
-- They hold the API's value verbatim and are never generated here.
--
-- notifications.issuer_id is an API-side id, NOT a local FK to issuers.id. Since
-- both sides are now UUIDs the two are structurally interchangeable and the
-- compiler cannot catch a mix-up — see CLAUDE.md Common Mistake #20.

DROP TABLE IF EXISTS "notification_reads" CASCADE;
DROP TABLE IF EXISTS "notifications" CASCADE;
DROP TABLE IF EXISTS "webhook_endpoints" CASCADE;
DROP TABLE IF EXISTS "agreement_drafts" CASCADE;
DROP TABLE IF EXISTS "document_templates" CASCADE;
DROP TABLE IF EXISTS "clients" CASCADE;
DROP TABLE IF EXISTS "products" CASCADE;
DROP TABLE IF EXISTS "user_issuer_access" CASCADE;
DROP TABLE IF EXISTS "issuers" CASCADE;
DROP TABLE IF EXISTS "tenant_api_keys" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;
DROP TABLE IF EXISTS "tenants" CASCADE;


-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateTable
CREATE TABLE "users" (
    "id" UUID NOT NULL,
    "email" TEXT NOT NULL,
    "first_name" TEXT,
    "last_name" TEXT,
    "password_hash" TEXT,
    "email_verified" BOOLEAN NOT NULL DEFAULT false,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "tenant_id" UUID,
    "role" TEXT,
    "invite_status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "invited_at" TIMESTAMP(3),
    "accepted_at" TIMESTAMP(3),
    "is_super_admin" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tenants" (
    "id" UUID NOT NULL,
    "api_tenant_id" UUID NOT NULL,
    "ruc" VARCHAR(13) NOT NULL,
    "business_name" TEXT NOT NULL,
    "trade_name" TEXT,
    "environment" TEXT NOT NULL DEFAULT 'sandbox',
    "status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "intended_tier" TEXT,
    "intended_billing_interval" TEXT,
    "pending_bank_transfer" JSONB,
    "contact_email" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "tenants_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tenant_api_keys" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "api_key_id" UUID NOT NULL,
    "label" TEXT NOT NULL,
    "environment" TEXT NOT NULL,
    "encrypted_key" TEXT NOT NULL,
    "last_four" VARCHAR(4) NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "revoked_at" TIMESTAMP(3),

    CONSTRAINT "tenant_api_keys_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "issuers" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "api_issuer_id" UUID NOT NULL,
    "branch_code" VARCHAR(3) NOT NULL,
    "issue_point_code" VARCHAR(3) NOT NULL,
    "business_name" TEXT NOT NULL,
    "trade_name" TEXT,
    "branch_address" TEXT,
    "is_default" BOOLEAN NOT NULL DEFAULT false,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "issuers_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "user_issuer_access" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "issuer_id" UUID NOT NULL,

    CONSTRAINT "user_issuer_access_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "products" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "main_code" VARCHAR(25) NOT NULL,
    "aux_code" VARCHAR(25),
    "description" TEXT NOT NULL,
    "unit_price" DECIMAL(14,6) NOT NULL,
    "tax_option" VARCHAR(10) NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "products_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "clients" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "id_type" VARCHAR(5) NOT NULL,
    "id_number" VARCHAR(20) NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "address" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "clients_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "document_templates" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "document_type" VARCHAR(2) NOT NULL DEFAULT '01',
    "name" TEXT NOT NULL,
    "data" JSONB NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "document_templates_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "notifications" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "api_notification_id" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "severity" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "message" TEXT NOT NULL,
    "metadata" JSONB,
    "issuer_id" UUID,
    "api_read_at" TIMESTAMP(3),
    "expires_at" TIMESTAMP(3),
    "api_created_at" TIMESTAMP(3) NOT NULL,
    "synced_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "notifications_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "notification_reads" (
    "id" UUID NOT NULL,
    "notification_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "read_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "notification_reads_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "agreement_drafts" (
    "id" UUID NOT NULL,
    "document_type" TEXT NOT NULL,
    "version" TEXT NOT NULL DEFAULT '',
    "content" TEXT NOT NULL,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "agreement_drafts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "webhook_endpoints" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "api_endpoint_id" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "encrypted_secret" TEXT NOT NULL,
    "event_types" TEXT[],
    "active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "webhook_endpoints_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- CreateIndex
CREATE INDEX "users_tenant_id_role_idx" ON "users"("tenant_id", "role");

-- CreateIndex
CREATE UNIQUE INDEX "tenants_api_tenant_id_key" ON "tenants"("api_tenant_id");

-- CreateIndex
CREATE UNIQUE INDEX "tenants_ruc_key" ON "tenants"("ruc");

-- CreateIndex
CREATE UNIQUE INDEX "tenant_api_keys_api_key_id_key" ON "tenant_api_keys"("api_key_id");

-- CreateIndex
CREATE INDEX "tenant_api_keys_tenant_id_is_active_idx" ON "tenant_api_keys"("tenant_id", "is_active");

-- CreateIndex
CREATE UNIQUE INDEX "issuers_api_issuer_id_key" ON "issuers"("api_issuer_id");

-- CreateIndex
CREATE INDEX "issuers_tenant_id_idx" ON "issuers"("tenant_id");

-- CreateIndex
CREATE UNIQUE INDEX "issuers_tenant_id_branch_code_issue_point_code_key" ON "issuers"("tenant_id", "branch_code", "issue_point_code");

-- CreateIndex
CREATE INDEX "user_issuer_access_user_id_tenant_id_idx" ON "user_issuer_access"("user_id", "tenant_id");

-- CreateIndex
CREATE UNIQUE INDEX "user_issuer_access_user_id_issuer_id_key" ON "user_issuer_access"("user_id", "issuer_id");

-- CreateIndex
CREATE INDEX "products_tenant_id_idx" ON "products"("tenant_id");

-- CreateIndex
CREATE INDEX "clients_tenant_id_idx" ON "clients"("tenant_id");

-- CreateIndex
CREATE INDEX "document_templates_tenant_id_document_type_idx" ON "document_templates"("tenant_id", "document_type");

-- CreateIndex
CREATE UNIQUE INDEX "document_templates_tenant_id_document_type_name_key" ON "document_templates"("tenant_id", "document_type", "name");

-- CreateIndex
CREATE INDEX "notifications_tenant_id_api_read_at_idx" ON "notifications"("tenant_id", "api_read_at");

-- CreateIndex
CREATE UNIQUE INDEX "notifications_tenant_id_api_notification_id_key" ON "notifications"("tenant_id", "api_notification_id");

-- CreateIndex
CREATE INDEX "notification_reads_user_id_idx" ON "notification_reads"("user_id");

-- CreateIndex
CREATE UNIQUE INDEX "notification_reads_notification_id_user_id_key" ON "notification_reads"("notification_id", "user_id");

-- CreateIndex
CREATE UNIQUE INDEX "agreement_drafts_document_type_key" ON "agreement_drafts"("document_type");

-- CreateIndex
CREATE INDEX "webhook_endpoints_tenant_id_idx" ON "webhook_endpoints"("tenant_id");

-- CreateIndex
CREATE UNIQUE INDEX "webhook_endpoints_tenant_id_api_endpoint_id_key" ON "webhook_endpoints"("tenant_id", "api_endpoint_id");

-- AddForeignKey
ALTER TABLE "users" ADD CONSTRAINT "users_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tenant_api_keys" ADD CONSTRAINT "tenant_api_keys_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "issuers" ADD CONSTRAINT "issuers_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "user_issuer_access" ADD CONSTRAINT "user_issuer_access_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "user_issuer_access" ADD CONSTRAINT "user_issuer_access_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "user_issuer_access" ADD CONSTRAINT "user_issuer_access_issuer_id_fkey" FOREIGN KEY ("issuer_id") REFERENCES "issuers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "products" ADD CONSTRAINT "products_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "clients" ADD CONSTRAINT "clients_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "document_templates" ADD CONSTRAINT "document_templates_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notification_reads" ADD CONSTRAINT "notification_reads_notification_id_fkey" FOREIGN KEY ("notification_id") REFERENCES "notifications"("id") ON DELETE CASCADE ON UPDATE CASCADE;

